### ISSUE TITLE
Contributors

### ISSUE THREAD

**Issue by JohnRobson** [webdevium/node-framework-stars#2]
Please, could you add "Contributors" to your table?  I think it's a piece of relevant information.  Thank you.

**Comment by vanodevium** [comment]
@JohnRobson 
No problems! Could you explain how this information should look like? Separate column, comma separated logins?
Should we take them from the API or leave them as static data?

**Comment by JohnRobson** [comment]
"Separate column" is a good idea.  "Contributors" is a good information to see how supported is the project. Thanks.
